### ISSUE TITLE
Move translations to Crowdin project

### ISSUE THREAD

**Issue by 2020LeftistStrikeBack** [LeftValues/leftvalues.github.io#27]
Just like PolitiScales did
https://www.politiscales.net/

**Comment by comradekingu** [comment]
Please don't use Crowdin, it is a lackluster tool in terms of ensuring quality, cumbersome to use, and is closed source software only-as-a-service that spies on users https://support.crowdin.com/cookies/.

I recommend using https://weblate.org/hosting/, which unlike Crowdin offers gratis hosting to all libre software projects, without requiring them to be non-commercial and contribute to their TM.

**Comment by ZerataX** [comment]
I think I've used weblate before and liked it, but that was when it was still fully open source

**Comment by comradekingu** [comment]
@ZerataX And it still is. Maybe you are thinking of Transifex. If so, I think you'll really enjoy Weblate.

**Comment by ZerataX** [comment]
oh I mixed up weblate with transifex a little here, but yeah I remember weblate being great. probably a good idea to port it to that

**Comment by ZerataX** [comment]
so I have pretty much everything setup. it's running here on my server:

https://l10n.dmnd.sh/projects/leftvalues/leftvalues/

and currently using the [weblate branch](https://github.com/LeftValues/leftvalues.github.io/tree/weblate) will change to master when people think it's fine.
It would be very nice to first also get a notifaction hook thingie setup so the weblate instance automatically updates when somebody pushes to the repo, but I don't have permissions to set that up.

@LeftValues you probably need to create a webhook or something, see here https://docs.weblate.org/en/latest/admin/continuous.html#updating-repositories

There's a ton of settings and stuff and I tried to set it up to the best of my abilities, but stuff is probably still not perfect, especially since it's still kinda my own solution and i'm not using any frameworks for this.

I also created this here https://github.com/LeftValues/leftvalues.github.io/blob/weblate/i18n.js#L23-L40 to automatically replace stuff that looks like `{{colors.syn}}`.

It would probably be good to remove all the html tags from the strings since that's more formatting than anything, but I guess it doesn't matter much.

Anyways so far I really love it, thanks for the suggestion @comradekingu

**Comment by ZerataX** [comment]
@LeftValues @sparkz9502 you closed this, but the website still can't push translations since the bot has no permissions

**Comment by LeftValues** [comment]
@ZerataX My bad, the bot should be invited now.

**Comment by ZerataX** [comment]
cool seems to work https://github.com/LeftValues/leftvalues.github.io/commit/39ae012338a90206690eb3d15e816fe2ecacec42
idk if you also added the webhook it's not super necessary, since I can set it to check periodically, but it would definitely be nice.

Anyways now people can add translations via the website and they will be merged every 24 hours.
I gave you admin permission for the project @LeftValues

**Comment by LeftValues** [comment]
@ZerataX Looks great, though a few issues seem to have arisen. Namely, the "There are __ questions in the test." line returns undefined, and the text colours for the axes in the index have broken in a few instances.

**Comment by ZerataX** [comment]
oh right I see the "There are __ questions in the test." on the index page, but where exactly are the colors missing?

**Comment by LeftValues** [comment]
For the English index, the "Union" text is greyed, on the German index "Utopisch", "Dezentralisiert", and "National" are greyed, and on the French index "Réformisme" and "Révolution" are greyed.

**Comment by ZerataX** [comment]
Ah okay I fixed the counter and I think those should just be fixable by editing here:
https://l10n.dmnd.sh/translate/leftvalues/leftvalues/en/?checksum=4db217563cbaf6a1

maybe I should have given these colors better names. it's not colors.synd but colors.syn

**Comment by ZerataX** [comment]
okay I think I got it

**Comment by ZerataX** [comment]
@TESSSERACT @Psykozis @2020LeftistStrikeBack @seunghaekim @reed-overflow @erikberter @LastWitchOfIllyrith @Jyunmau sorry for the spam, just wanted to again thank you for your work and draw attention to https://l10n.dmnd.sh/projects/leftvalues/leftvalues/

if you ever again want to add or review the translations it should now be a lot more straightforward!

**Comment by Psykozis** [comment]
You r' welcome!
@Psykozis <marlonsigales@hotmail.com> in here.
Portuguese it's done! reviewed and checked.
Hugs, health, mutual-aid and freedom.

Att.,
Marlon Soares Sigales


*Engenheiro Eletrônico*Contatos:( marlonsigales@gmail.com |
msoaressigales928@gmail.com | marlonsigales@hotmail.com)


Em seg., 4 de mai. de 2020 às 15:27, Jona Abdinghoff <
notifications@github.com> escreveu:

**Comment by comradekingu** [comment]
Added to https://github.com/WeblateOrg/weblate/wiki/References
