### ISSUE TITLE
Problem with question

### ISSUE THREAD

**Issue by X-Clyder** [LeftValues/leftvalues.github.io#44]
One of the questions in the test - "**Total economic and social equality is realistically possible to achieve.**"
And answering "agree" to that question moves you towards utopianism. Why? Aren't social and economic equality the main provisions in Marxism?

**Comment by LeftValues** [comment]
Not at all, though it is a common misconception that I can hardly blame you for. Marx regarded the concept of equality of outcome as bourgeois and utopian. The reason he believed this is because he viewed introducing a system of equal wealth as reinforcing the concept of wealth as a measure of an individual's worth. He called this a form of "crude communism", through which the community operates as a collective capitalist. He instead believed that inequality would be _reduced_ by socializing the means of production, while eliminating inequality as a whole would be undesirable and likely impossible.
